project:
  title: "Functions"
  output-dir: docs

format:
  html:
    toc: true
    toc-title: Contents
    toc-location: right
    html-math-method: katex
    self-contained: true
    citations-hover: true
    footnotes-hover: true
    link-external-icon: true
    editor: source
  revealjs:
    self-contained: true
    code-fold: false
    code-overflow: wrap
    footer: "[Dyerlab](https://dyerlab.org)"
    background-transition: fade
    theme: default
    editor: source
    title-slide-attributes: 
      data-background-image: "media/contour.png"
      data-background-position: "right"
      data-background-size: initial
